version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/adrien-la-boudi/week7day3-batch23:master
    ports:
      - '8001:8000' # Opens port 8000 on the container's side, sends data to port 8001 on local machine side
    env_file:
      - ./envs/prod.env
    command: "sh /scripts/prod.sh"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: