name: Deployment
run-name: ${{ github.sha }}
on: [push]
jobs:
  push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t test-github-actions .

  deploy:
    runs-on: self-hosted
    steps:
      - run: docker compose -f docker-compose.deploy.yml pull
      - run: docker compose -f docker-compose.deploy.yml down --remove-orphans
      - run: docker volume ls -q -f name=build | xargs -r docker volume rm
      - run: docker compose -f docker-compose.deploy.yml up -d