name: Deployment
run-name: ${{ github.sha }}
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ github.job }} .

  deploy:
    runs-on: self-hosted
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - run: docker compose -f docker-compose.deploy.yml pull
      - run: docker compose -f docker-compose.deploy.yml down --remove-orphans
      - run: docker volume ls -q -f name=build | xargs -r docker volume rm
      - run: docker compose -f docker-compose.deploy.yml up -d