name: Deployment
run-name: ${{ github.sha }}
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ github.sha }}:${{ github.ref_name }} .

  lint:
    runs-on: self-hosted
    steps:
      - run: export GITHUB_SHA=${{ github.sha }}
      - run: export GITHUB_REF_NAME=${{ github.ref_name }}
      - run: echo "${GITHUB_SHA}:${GITHUB_REF_NAME}"
      - run: docker compose -p "$GITHUB_SHA" -f docker-compose.ci.yml run backend flake8 .

  deploy:
    runs-on: self-hosted
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - run: docker compose -f docker-compose.deploy.yml pull
      - run: docker compose -f docker-compose.deploy.yml down --remove-orphans
      - run: docker volume ls -q -f name=build | xargs -r docker volume rm
      - run: docker compose -f docker-compose.deploy.yml up -d